import mongoose from "mongoose";
import Inventory from "../models/Inventory.js";
import Order from "../models/Order.js";
import Reservation from "../models/Reservation.js";
const id=(p)=>`${p}-${Date.now()}-${Math.floor(100+Math.random()*900)}`;
function validateItems(items){if(!Array.isArray(items)||!items.length){const e=new Error("At least one item is required");e.statusCode=400;throw e;}for(const x of items)if(!x.inventoryId||!Number.isInteger(x.quantity)||x.quantity<1){const e=new Error("Each item requires inventoryId and a positive integer quantity");e.statusCode=400;throw e;}}
export async function createReservation({orderId,items,durationMinutes}){validateItems(items);const s=await mongoose.startSession();try{let created;await s.withTransaction(async()=>{const order=await Order.findById(orderId).session(s);if(!order){const e=new Error("Order not found");e.statusCode=404;throw e;}if(order.reservationStatus==="Active"){const e=new Error("Order already has an active reservation");e.statusCode=409;throw e;}const out=[];for(const x of items){const inv=await Inventory.findById(x.inventoryId).session(s);if(!inv){const e=new Error(`Inventory item not found: ${x.inventoryId}`);e.statusCode=404;throw e;}const available=inv.totalStock-inv.reservedStock;if(available<x.quantity){const e=new Error(`Insufficient stock for ${inv.name}. Available: ${available}, requested: ${x.quantity}`);e.statusCode=409;throw e;}inv.reservedStock+=x.quantity;await inv.save({session:s});out.push({inventoryId:inv._id,productName:inv.name,sku:inv.sku,quantity:x.quantity});}const minutes=Number(durationMinutes)>0?Number(durationMinutes):Number(process.env.RESERVATION_DURATION_MINUTES||30);[created]=await Reservation.create([{reservationNumber:id("RES"),order:order._id,items:out,expiresAt:new Date(Date.now()+minutes*60000)}],{session:s});order.reservationStatus="Active";await order.save({session:s});});return Reservation.findById(created._id).populate("order");}finally{await s.endSession();}}
export async function releaseReservation(reservationId,reason="Released"){const s=await mongoose.startSession();try{let updated;await s.withTransaction(async()=>{const r=await Reservation.findById(reservationId).session(s);if(!r){const e=new Error("Reservation not found");e.statusCode=404;throw e;}if(r.status!=="Active"){const e=new Error(`Reservation is already ${r.status.toLowerCase()}`);e.statusCode=409;throw e;}for(const x of r.items){const inv=await Inventory.findById(x.inventoryId).session(s);if(inv){inv.reservedStock=Math.max(0,inv.reservedStock-x.quantity);await inv.save({session:s});}}r.status=reason==="Expired"?"Expired":"Released";r.releasedAt=new Date();await r.save({session:s});await Order.findByIdAndUpdate(r.order,{reservationStatus:r.status},{session:s});updated=r;});return Reservation.findById(updated._id).populate("order");}finally{await s.endSession();}}
export async function confirmOrder(orderId){const s=await mongoose.startSession();try{let updated;await s.withTransaction(async()=>{const order=await Order.findById(orderId).session(s);if(!order){const e=new Error("Order not found");e.statusCode=404;throw e;}if(order.reservationStatus!=="Active"){const e=new Error("Order does not have an active reservation");e.statusCode=409;throw e;}const r=await Reservation.findOne({order:order._id,status:"Active"}).session(s);if(!r){const e=new Error("Active reservation not found for this order");e.statusCode=409;throw e;}for(const x of r.items){const inv=await Inventory.findById(x.inventoryId).session(s);if(!inv||inv.reservedStock<x.quantity||inv.totalStock<x.quantity){const e=new Error(`Inventory state is invalid for ${x.productName}`);e.statusCode=409;throw e;}inv.totalStock-=x.quantity;inv.reservedStock-=x.quantity;await inv.save({session:s});}r.status="Confirmed";r.confirmedAt=new Date();await r.save({session:s});order.reservationStatus="Confirmed";order.status="Processing";await order.save({session:s});updated=order;});return Order.findById(updated._id).populate("items.inventoryId");}finally{await s.endSession();}}
export async function releaseExpiredReservations(){const rs=await Reservation.find({status:"Active",expiresAt:{$lte:new Date()}}).select("_id");let n=0;for(const r of rs){try{await releaseReservation(r._id,"Expired");n++;}catch(e){console.error(`Could not release ${r._id}:`,e.message);}}return n;}
